### ISSUE TITLE
xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by cn0xroot** [telekom/5g-trace-visualizer#26]
thanks for your nice project

when I try to use it,something  error :

```
python3 trace_visualizer.py -wireshark "OS" ./doc/free5gc.pcap
DEBUG:root:Searching for plantuml.jar under 5g-trace-visualizer/plantuml.jar
DEBUG:root:Found plantuml.jar

DEBUG:root:Platform system detected: Linux
5G Wireshark trace visualizer for 5G protocol
Input file: ./doc/free5gc.pcap
Pods YAML file: None
Maximum messages per file: 100
Debug: None
String un-escaping for HTTP requests: True
OpenStack servers file: None
HTTP/2 headers to ignore: None
Diagrams to output: ip,k8s_pod,k8s_namespace
Simple diagrams: False
Force show frames if using simple diagrams:
Show PFCP/GTPv2 heartbeat messages: False
Show HTTP/2 in spurious TCP retransmission messages: True
Ignore PFCP packet duplicates: True
Show timestamp in diagram: False
Show self-messages: False

DEBUG:root:Preparing call for Wireshark version OS
DEBUG:root:Wireshark call for ./doc/free5gc.pcap. Version OS, HTTP/2 ports: 32445,5002,5000,32665,80,32077,5006,8080,3000
DEBUG:root:tshark path: /usr/bin/tshark
DEBUG:root:Received HTTP/2 port list: 32445,5002,5000,32665,80,32077,5006,8080,3000
DEBUG:root:Using Wireshark version OS
DEBUG:root:Wireshark supports nas-5gs.null_decipher option. Applying
DEBUG:root:Generating PDML files from PCAP to ./doc/free5gc_OS.pdml
DEBUG:root:['/usr/bin/tshark', '-r', './doc/free5gc.pcap', '-2', '-d', 'tcp.port==32445,http2', '-d', 'tcp.port==5002,http2', '-d', 'tcp.port==5000,http2', '-d', 'tcp.port==32665,http2', '-d', 'tcp.port==80,http2', '-d', 'tcp.port==32077,http2', '-d', 'tcp.port==5006,http2', '-d', 'tcp.port==8080,http2', '-d', 'tcp.port==3000,http2', '-o', 'nas-5gs.null_decipher: TRUE', '-Y', '(http2 and (http2.type == 0 || http2.type == 1)) or ngap or nas-5gs or pfcp or gtpv2 or diameter or radius or gtpprime or icmp or icmpv6.type == 134', '-T', 'pdml', '-J', 'http2 ngap pfcp gtpv2 tcp diameter radius gtpprime icmp icmpv6', '-n']
Running as user "root" and group "root". This could be dangerous.
tshark: -o flag "nas-5gs.null_decipher: TRUE" specifies unknown preference
DEBUG:root:Output ./doc/free5gc_OS.pdml
DEBUG:root:PDML file path(s): ['./doc/free5gc_OS.pdml']
DEBUG:root:Importing main file ./doc/free5gc_OS.pdml
DEBUG:root:Cleaning up PDML file ./doc/free5gc_OS.pdml
DEBUG:root:Finished cleaning up PDML file
DEBUG:root:Parsing PDML file ./doc/free5gc_OS.pdml
Traceback (most recent call last):
  File "trace_visualizer.py", line 1918, in <module>
    args.show_selfmessages)
  File "trace_visualizer.py", line 1177, in import_pdml
    tree = read_cleanup_and_load_pdml_file(file_path)
  File "trace_visualizer.py", line 1139, in read_cleanup_and_load_pdml_file
    parsed_et = ET.parse(file_path)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

How to make it work fine? Thanks

**Comment by OrlandoST** [comment]
Can you attach your **.pcap** file and **.pdml** file?

In my case all work well:
```bash
python3 trace_visualizer.py -wireshark "OS" ./doc/free5gc.pcap
DEBUG:root:Searching for plantuml.jar under /home/.../5g-trace-visualizer/plantuml.jar
DEBUG:root:Found plantuml.jar

DEBUG:root:Platform system detected: Linux
5G Wireshark trace visualizer for 5G protocol
Input file: ./doc/free5gc.pcap
Pods YAML file: None
Maximum messages per file: 100
Debug: None
String un-escaping for HTTP requests: True
OpenStack servers file: None
HTTP/2 headers to ignore: None
Diagrams to output: ip,k8s_pod,k8s_namespace
Simple diagrams: False
Force show frames if using simple diagrams: 
Show PFCP/GTPv2 heartbeat messages: False
Show HTTP/2 in spurious TCP retransmission messages: True
Ignore PFCP packet duplicates: True
Show timestamp in diagram: False
Show self-messages: False

DEBUG:root:Preparing call for Wireshark version OS
DEBUG:root:Wireshark call for ./doc/free5gc.pcap. Version OS, HTTP/2 ports: 32445,5002,5000,32665,80,32077,5006,8080,3000
DEBUG:root:tshark path: /usr/bin/tshark
DEBUG:root:Received HTTP/2 port list: 32445,5002,5000,32665,80,32077,5006,8080,3000
DEBUG:root:Using Wireshark version OS
DEBUG:root:Wireshark supports nas-5gs.null_decipher option. Applying
DEBUG:root:Generating PDML files from PCAP to ./doc/free5gc_OS.pdml
DEBUG:root:['/usr/bin/tshark', '-r', './doc/free5gc.pcap', '-2', '-d', 'tcp.port==32445,http2', '-d', 'tcp.port==5002,http2', '-d', 'tcp.port==5000,http2', '-d', 'tcp.port==32665,http2', '-d', 'tcp.port==80,http2', '-d', 'tcp.port==32077,http2', '-d', 'tcp.port==5006,http2', '-d', 'tcp.port==8080,http2', '-d', 'tcp.port==3000,http2', '-o', 'nas-5gs.null_decipher: TRUE', '-Y', '(http2 and (http2.type == 0 || http2.type == 1)) or ngap or nas-5gs or pfcp or gtpv2 or diameter or radius or gtpprime or icmp or icmpv6.type == 134', '-T', 'pdml', '-J', 'http2 ngap pfcp gtpv2 tcp diameter radius gtpprime icmp icmpv6', '-n']
DEBUG:root:Output ./doc/free5gc_OS.pdml
DEBUG:root:PDML file path(s): ['./doc/free5gc_OS.pdml']
DEBUG:root:Importing main file ./doc/free5gc_OS.pdml
DEBUG:root:Cleaning up PDML file ./doc/free5gc_OS.pdml
DEBUG:root:Finished cleaning up PDML file
DEBUG:root:Parsing PDML file ./doc/free5gc_OS.pdml
DEBUG:root:Finished parsing PDML file
DEBUG:root:Importing 0 alternative files
DEBUG:root:Checking for malformed packets (can decode with more than one WS version)
DEBUG:root:Root tag is "pdml": OK
DEBUG:root:1: Internet Protocol Version 4, Src: 10.200.200.1, Dst: 10.200.200.101
DEBUG:root:2: Internet Protocol Version 4, Src: 10.200.200.101, Dst: 10.200.200.1
DEBUG:root:13: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:14: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:15: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:44: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:45: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:72: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:76: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:171: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:174: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:175: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:216: Internet Protocol Version 4, Src: 10.200.200.1, Dst: 10.200.200.101
DEBUG:root:219: Internet Protocol Version 4, Src: 10.200.200.101, Dst: 10.200.200.1
DEBUG:root:228: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:233: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
DEBUG:root:243: Internet Protocol Version 4, Src: 10.200.200.1, Dst: 10.200.200.101
DEBUG:root:245: Internet Protocol Version 4, Src: 10.200.200.101, Dst: 10.200.200.1
DEBUG:root:249: Internet Protocol Version 4, Src: 60.60.0.1, Dst: 60.60.0.101
DEBUG:root:249 (GTP): Internet Protocol Version 4, Src: 10.200.200.1, Dst: 10.200.200.102
DEBUG:root:250: Internet Protocol Version 4, Src: 60.60.0.101, Dst: 60.60.0.1
DEBUG:root:250 (GTP): Internet Protocol Version 4, Src: 10.200.200.102, Dst: 10.200.200.1
DEBUG:root:Generating Plant UML file for ip
DEBUG:root:Simple diagrams: False
DEBUG:root:Force-ordering participants: ['']
DEBUG:root:Final participant order: [('participant', '"N1\\n(127.0.0.1)" as 127.0.0.1', '127.0.0.1', {'N1'}, None), ('participant', '"10.200.200.1"', '10.200.200.1', set(), None), ('participant', '"10.200.200.101"', '10.200.200.101', set(), None), ('participant', '"10.200.200.102"', '10.200.200.102', set(), None)]
DEBUG:root:Outputting PlantUML file to ./doc/free5gc_OS.puml
Converting .puml files to SVG
DEBUG:root:Generating SVG diagram 1/1: java -Djava.awt.headless=true -jar "/home/.../5g-trace-visualizer/plantuml.jar" "./doc/free5gc_OS.puml" -tsvg
```

**Comment by OrlandoST** [comment]
Maybe you need to update tshark or temporaly remove this option for troubleshooting
```
tshark: -o flag "nas-5gs.null_decipher: TRUE" specifies unknown preference
```

**Comment by cn0xroot** [comment]
> Maybe you need to update tshark or temporaly remove this option for troubleshooting
> 
> ```
> tshark: -o flag "nas-5gs.null_decipher: TRUE" specifies unknown preference
> ```

Update wireshark tshark from  2.6 to 3.6. project work fine now.  🙏  Thanks

**Comment by jkolom** [comment]
The cause of the error is that in the Windows version (where this was initially implemented) the ``tshark`` version is inferred from the folder name. In Linux, since "portable" Wireshar does not exist and one just uses an installed one, that is not possible. Older ``tshark`` versions do not support ``nas-5gs.null_decipher``, so when the parameter is blindly used based on the ``OS`` parameter, ``tshark`` complains. It should be possible to add a pre-check of the ``tshark`` version when ``OS`` is used by extending the check [here](https://github.com/telekom/5g-trace-visualizer/blob/b69e4e6a3a0305ee86fe3b8c4c69a3c17deeda48/trace_visualizer.py#L1669-L1672) to first call ``Tshark`` to output the version number, read it and fill in a variable with it.
