### ISSUE TITLE
Trace visualizer Crashes 

### ISSUE THREAD

**Issue by nitinbhat** [telekom/5g-trace-visualizer#30]
trace visualizer crashed when tried to generate svg file out of pcap

_python3 trace_visualizer.py -wireshark "OS" -http2ports "1000-65535" ../../Documents/open5gs-lo.pcap_

`DEBUG:root:906: Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.5
Traceback (most recent call last):
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 1951, in <module>
    puml_files = import_pdml(
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 1387, in import_pdml
    nas_request = parse_nas_proto(frame_number, ngap_proto)
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 210, in parse_nas_proto
    return parse_nas_proto_el(frame_number, el, multipart_proto)
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 228, in parse_nas_proto_el
    nas_5g_dict = nas_5g_proto_to_dict(nas_5g_proto)
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 175, in nas_5g_proto_to_dict
    return xml2json(nas_5g_proto)
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 168, in xml2json
    parsed_tree = recursiv(root)
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 135, in recursiv
    data_to_append = recursiv(child_to_traverse)
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 135, in recursiv
    data_to_append = recursiv(child_to_traverse)
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 135, in recursiv
    data_to_append = recursiv(child_to_traverse)
  [Previous line repeated 13 more times]
  File "/Users/ni.bhat/Desktop/5g-trace-visualizer/trace_visualizer.py", line 127, in recursiv
    logging.DEBUG('Found repeated child element {0}. Renamed to {1}'.format(original_child_name, child_name))
TypeError: 'int' object is not callable`

**Comment by jkolom** [comment]
Is there a chance you could post your pcap or pdml file? (even if edited)
There is zero chance to find out what happened if one cannot reproduce the error

**Comment by nitinbhat** [comment]
Attaching pcap and pdml files 
[open5gs-lo.zip](https://github.com/telekom/5g-trace-visualizer/files/11442974/open5gs-lo.zip)

**Comment by nitinbhat** [comment]
Is there any workaround to avoid crash? I see this being closed

**Comment by jkolom** [comment]
It seems like it was a mixture of a log line crashing AND plantUML not liking a colom (":") in the participant list. Since IPv6 is not that supported in k8s, we never had this issue when this script was developed. The solution is not ideal (no alias in the legend for ::1), but it now runs and outputs the SVG. Could you please confirm that the solution works?
PS: I was still writing this text 😉

**Comment by nitinbhat** [comment]
Thank you. I am not observing crash with latest of master.
