### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ashutoshpm** [telekom/5g-trace-visualizer#37]
I am getting this error while executing the script,
I am runnign the script on CentOS

 python3 trace_visualizer.py -wireshark "OS" 53_20240507T094621.pcap
Traceback (most recent call last):
  File "trace_visualizer.py", line 13, in <module>
    import parsing.http
  File "/home/mcn/NPNscripts/5gtracevisualizer/5g-trace-visualizer-master/parsing/http.py", line 11, in <module>
    import parsing.mime_multipart
  File "/home/mcn/NPNscripts/5gtracevisualizer/5g-trace-visualizer-master/parsing/mime_multipart.py", line 23, in <module>
    class MultipartMimeMessage(NamedTuple):
  File "/home/mcn/NPNscripts/5gtracevisualizer/5g-trace-visualizer-master/parsing/mime_multipart.py", line 27, in MultipartMimeMessage
    mime_headers: list[MimeHeader]
TypeError: 'type' object is not subscriptable
[mcn@localhost 5g-trace-visualizer-master]$ python trace_visualizer.py -wireshark "OS" 53_20240507T094621.pcap
Traceback (most recent call last):
  File "trace_visualizer.py", line 13, in <module>
    import parsing.http
  File "/home/mcn/NPNscripts/5gtracevisualizer/5g-trace-visualizer-master/parsing/http.py", line 11, in <module>
    import parsing.mime_multipart
  File "/home/mcn/NPNscripts/5gtracevisualizer/5g-trace-visualizer-master/parsing/mime_multipart.py", line 23, in <module>
    class MultipartMimeMessage(NamedTuple):
  File "/home/mcn/NPNscripts/5gtracevisualizer/5g-trace-visualizer-master/parsing/mime_multipart.py", line 27, in MultipartMimeMessage
    **mime_headers: list[MimeHeader]**
**TypeError: 'type' object is not subscriptable**

**Comment by jkolom** [comment]
Hi,
sorry for the late reply, I missed the email.
In order to be able to replicate the error, please provide a packet capture that I can use to test the error. While it is clear from the message that I may have missed something with the Mime parsing, it is not possible to know what unless I have a packet capture.
If you want to keep some information out of the post, you can just export some relevant packets instead of providing the whole trace.
